services:
  package:
    build: ./
    image: isas_subpackage-template
    container_name: isas_subpackage-template_dev
    volumes:
      - .:/root/workspace
      - ${HOST_DATADRIVE_PATH}/Subpackage:/root/datadrive
      - ${HOST_SSH_PATH}:/root/.ssh
    env_file:
      - .env
